server:
  port: 8087
  shutdown: immediate
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5430}/${DB_NAME:popcorn_db}
    username: ${STORE_DB_USERNAME:order_query_app}
    password: ${STORE_DB_PASSWORD:query123}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type:
          preferred_enum_jdbc_type: VARCHAR

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5320}/${DB_NAME:popcorn_db}
    user: ${STORE_FLYWAY_USERNAME:order_query_migrator}
    password: ${STORE_FLYWAY_PASSWORD:query123}
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration/schema,classpath:db/migration/seed
    default-schema: order_query
    schemas: order_query
    clean-disabled: false


jwt:
  secret: ${JWT_SECRET:dGVzdC1qd3Qtc2VjcmV0LWtleS1mb3ItbG9jYWwtZGV2ZWxvcG1lbnQtb25seS1kb25vdC11c2UtaW4tcHJvZHVjdGlvbg==}
  expiration: 3600000

passport:
  secret: ${PASSPORT_SECRET:passport-shared-secret}
  ttl-seconds: 60


