services:
  db:
    image: postgres:18
    container_name: popcorn-db
    environment:
      POSTGRES_DB: ${DB_NAME:-popcorn_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/main/resources/db/migration/schema/V0__init.sql:/docker-entrypoint-initdb.d/V0__init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-popcorn_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: popcorn-backend
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
