services:
  db:
    image: postgres:15-alpine
    container_name: popcorn-db
    environment:
      POSTGRES_DB: ${DB_NAME:-popcorn_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "5432:5432"
      - "5430:5432"
    volumes:
      - ./V0__init.sql:/docker-entrypoint-initdb.d/V0__init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-popcorn_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    image: ${DOCKERHUB_USERNAME}/popcorn-backend:latest
    container_name: popcorn-backend
    env_file:
      - ./.env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    container_name: popcorn-frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
      - NEXT_PUBLIC_TOSS_CLIENT_KEY=${TOSS_CLIENT_KEY}
    depends_on:
      - app
    ports:
      - "3000:3000"
    restart: always
