spring:
  application:
    name: checkIns
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

---

spring:
  config:
    import: classpath:security/application-local.yml
    activate:
      on-profile: local

---

spring:
  config:
    import: classpath:security/application-dev.yml
    activate:
      on-profile: dev

---

spring:
  config:
    import: classpath:security/application-prod.yml
    activate:
      on-profile: prod

app:
  version: ${APP_VERSION:0.0.1-SNAPSHOT}

springdoc:
  api-docs:
    path: ${SWAGGER_API_DOCS_PATH:/v3/api-docs}
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
    operations-sorter: alpha
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
