server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: checkIns
          uri: http://localhost:8086     # checkIns 모듈
          predicates:
            - Path=/api/qr/**  # QR 관련 요청은 checkIns로
        - id: order-service
          uri: http://localhost:8084     # order 모듈
          predicates:
            - Path=/api/orders/**  # 주문 관련 요청은 order로
        - id: payment-service
          uri: http://localhost:8085     # payment 모듈
          predicates:
            - Path=/api/payments/**  # 결제 관련 요청은 payment로
        - id: backend
          uri: http://localhost:8081     # 모놀리식 backend
          predicates:
            - Path=/api/v1/**               # /api 로 시작하면 backend로 라우팅
        - id: user-service
          uri: http://localhost:8082     # 모놀리식 backend
          predicates:
            - Path=/api/users/**          # user-service
        - id: stores
          uri: http://localhost:8083
          predicates:
            - Path=/api/stores/**         # stores
  webflux:
    base-path: /

jwt:
  secret: bXlWZXJ5TG9uZ1NlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvblRoYXRJczI1NkJpdHNMb25nMTIzNDU=

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: http://localhost:8082/v3/api-docs
      - name: order-service
        url: http://localhost:8084/v3/api-docs
      - name: payment-service
        url: http://localhost:8085/v3/api-docs
        
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty.http.client: DEBUG
