server:
  port: 8080
  shutdown: immediate
spring:
  datasource:
    url: ${DB_URL_LOCAL}
    username: ${DB_USER_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
    driver-class-name: org.postgresql.Driver
 
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true     # 기존 DB에 스키마가 있어도 baseline 잡고 시작
    locations: classpath:db/migration/schema

