server:
  port: 8080
  shutdown: immediate
spring:
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}
    driver-class-name: org.postgresql.Driver
 
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true     
    locations: classpath:db/migration/schema

